const
  HASH_MeLibrary            = $00D737D9;
  HASH_ModuleRunResult      = $0ACA7DA4;
  HASH_Kernel32_DLL         = $0B9F5B9C;   //'kernel32.dll'
  HASH_IpHlpApi_DLL         = $02B0FA4C;   //'IPHLPAPI.dll'
  HASH_WSock32_DLL          = $0E39AC7C;   //'wsock32.dll'
  HASH_User32_DLL           = $056290AC;   //'user32.dll'
  HASH_AdvApi32_DLL         = $083E8F4C;   //'advapi32.dll'
                                               
  HASH_OutputDebugStringA   = $05554ED1; 

const
  HASH_ProceIsStillValid     = $0AA7BB64;
  HASH_ProceIsValid          = $0BDD7744;
  HASH_ProceIsListing        = $07DF1717;
  HASH_GetModuleMD5          = $0D3A1345;
  HASH_ProceIDToName         = $0D015D95;

  HASH_EnumerateProcess      = $04D1B183;
  HASH_EnumerateProceDllFuns = $095DA313;
  HASH_EnumerateProceHandles = $0C2FAB83;
  HASH_EnumerateProceWindows = $0BAFAFD3;
  HASH_EnumerateProceLocalFiles = $05B9D703;

const
  HASH_HashTbl_Create    = $05FB1565;
  HASH_HashTbl_Destroy   = $0F70A919;
  HASH_HashTbl_Delete    = $05F58965;
  HASH_HashTbl_Clear     = $0E51D152;
  HASH_HashTbl_Find      = $03E5D1A4;
  HASH_HashTbl_Insert    = $05BEF994;
  HASH_HashTbl_Count     = $0E519204;

const
  HASH_DebugPrinter          = $01E54162;
  HASH_GetSpecialFolder      = $08FFCF72;
  HASH_SendIpcMessage        = $0B8094A5;
  HASH_SendEchoMessage       = $03215915;
  HASH_RunAsDefault         = $0DE05064;

  HASH_StrEnd               = $05896A24;
  HASH_StrCat               = $05896764;
  HASH_StrCopy              = $08968409;
  HASH_StrLen               = $0589709E;
  HASH_StrComp              = $08968470;

  HASH_AllocMem             = $011385FD;
  HASH_FreeMem              = $0B69A1DD;

  HASH_GetRandomGUID        = $04A8AFB4;
  HASH_ForceDirectories     = $0F283F53;
  HASH_ExtractFilePath      = $056F84F8;
  HASH_RunAppWithUserA      = $0ABF7621;
  HASH_FormatTraceRouter    = $0CC68AC2;

  HASH_GetUpperNameHash     = $0049DBB8;    

  HASH_GetBaseBoard          = $032DB004;
  HASH_GetSMBiosVersion      = $02B5042E;
  HASH_GetBiosName           = $0E0D8E75;
  HASH_GetBIOSSerialNumber   = $04EC15C2;
  HASH_GetFirstDiskInfo      = $049CF0AF;
  HASH_GetProcessorInfo      = $033122BF;
  HASH_GetPhysicalMemoryInfo = $0A5374DF;
  HASH_GetOperatingSystem    = $025292FD;
  HASH_GetVideoCardName      = $0CB51DF5;
  HASH_GetSoundCardName      = $0E27B8F5;

const
  HASH_DeleteFileA          = $08D28031;
  HASH_CopyFileA            = $05DAA8D1;
  HASH_GetModuleFileNameA   = $0DB86961;
  HASH_Sleep                = $005809A0;
